import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Roboto , Montserrat,Playfair_Display} from "next/font/google";
import "./globals.css";
import Link from "next/link";

const myFont = Playfair_Display({
  // weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-playfair-display",
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body
      className={`${myFont.variable} ` + `${geistSans.variable} `}
      >
         
        {children}

              


        

      </body>
    </html>
  );
}
